#!/usr/bin/env node
// -*- mode: Javascript; -*-

console.log(' - starting the loading of the mezzapp database');

var FIXTURE = "./fixtures/vps.csv";
var mysql = require('mysql');
var fs = require('fs');

var cx = mysql.createConnection({
    host: 'localhost',
    database: 'mezzapp',
    user: 'mezzapp',
    password: 'mezzapp'});

cx.connect();

fs.readFile(FIXTURE, parselines);

// read and parse a line
function parselines(err, data) {
    console.log(data);
    process.exit(0);
}

var rs = cx.query('');

cx.on('drain', function() {
    console.log(' -- drain event catched');
});

rs.on('error', function(err) {
    console.log(' -- error event catched');
    console.log(err);
});

rs.on('fields', function(_fields, index) {
    console.log(' -- fields event catched');
    console.log(_fields);
});

rs.on('result', function(row) {
    console.log(' -- result event catched');
    console.log(row);
});

cx.on('end', function() {
    console.log(' -- end event catched');
});

cx.end();
