#!/bin/bash

# tests for the users' routines
# 'boxuser' should be an unprivileged user on the test machine

__DEBUG__=1

USER=boxuser

source ../utilities

print_banner "Test user's existence"

echo $(validate_user root) $?

echo $(validate_user) $?

echo $(validate_user dontexist) $?

echo $(user_home root) $?

echo $(user_home) $?

echo $(user_subuids boxuser)

echo $(user_subgids boxuser)
