#!/bin/bash

# WARNING almost all these tests need to be evaluate as root,
#         do that inside an environment you are ready to trash.
#         a KVM VM using snapshots is the next best thing...
#
#  the tests expect that the unprivileged 'boxuser' exists on the
# machine before run.

# maybe changed before running the tests

__DEBUG__=1

USER=boxuser

# everything should with the preceding settings

source ../utilities
source ../recipes/containers

print_banner "Testing validate_container"
validate_container $USER mybox

print_banner "Testing enable_unprivileged_containers"
enable_unprivileged_containers
assert "$(/sbin/sysctl -n kernel.unprivileged_userns_clone) = 1" \
       "kernel.unprivileged_userns_clone = 1"

print_banner "Creating user cgroups"
create_user_cgroups $USER

print_banner "Creating User's LXC folders"
create_user_lxc_folders $USER

print_banner "Creating User's default container configuration"
create_user_lxc_default_config $USER

print_banner "Destroying user cgroups"
destroy_user_cgroups $USER

print_banner "Testing disable_unprivileged_containers"
disable_unprivileged_containers
assert "$(/sbin/sysctl -n kernel.unprivileged_userns_clone) = 0" \
       "kernel.unprivileged_userns_clone = 0"
