#!/bin/bash

source ../utilities

read_configuration ./fixtures/makeuser.ini

print_banner "All configuration keys"
echo ${config[*]}

print_banner "Some individual configuration keys"
echo "Global_SOURCE :: " ${config["Global_SOURCE"]}
echo "Global_MYSQL_SERVER :: " ${config["Global_MYSQL_SERVER"]}
echo "Global_PUBLIC_IP :: " ${config["Global_PUBLIC_IP"]}
echo "Global_BACKUP_DIR :: " ${config["Global_BACKUP_DIR"]}
