#!/bin/bash

__DEBUG__=1

set -e

SCRIPTDIR=$(dirname $0)

source $SCRIPTDIR/../utilities
source $SCRIPTDIR/cgroups_utils

#
# LXC management routines
#

start_user_container () {
    local user=$1
    local box=$2

    su - $user \
       -c "cgm movepid all $user $$ && lxc-start -n $box -d"
}

startbox () {
    local user=$1
    local box=$2

    echo " -- starting ${user}'s box ${box}"

    enable_unprivileged_containers
    create_user_groups $user
    start_user_container $user $box
}

stopbox () {
    echo " -- stopping ${user}'s box ${box}"
}

status () {
    local user=$1
    local box=$2

    echo " -- status of ${user}'s box ${box}"
}


#
# framework callable routines
#

_usage () {
    cat <<EOF

$(basename $0) start|stop|status --user=... --box=...

The Mezzapp user's LXC container controller script.

EOF
}

_initargs () {
    _start=0
    _stop=0
    _status=0

    user=""
    box=""
    help=0
    syslog=0
}

_validateargs () {
    echo $ARGC $user $box $_status
}

_run () {
    if [ $_start = 1 ]; then
        startbox $user $box
    fi

    if [ $_stop = 1 ]; then
        stopbox $user $box
    fi

    if [ $_status = 1 ]; then
        status $user $box
    fi
}

source $SCRIPTDIR/../base

initargs help user: box:
initcommands start stop status

run $@
