#!/bin/bash

set -e

source ../utilities

source ./cgroups_utils

CGM="/usr/bin/cgm"
SU="/bin/su"

#
# LXC parameters
#


if ! grep $USER /etc/lxc/lxc-usernet > /dev/null 2>&1; then
    echo "$USER br0 10" >> /etc/lxc/lxc-usernet
fi

configure_user () {
    mkdir -p /home/${USER}/.cache/lxc
    mkdir -p /home/${USER}/.config/lxc
    mkdir -p /home/${USER}/.local/share/lxc/

    if [ ! -f /home/${USER}/.config/lxc/default.conf ]; then
        cat > /home/${USER}/.config/lxc/default.conf <<EOF
lxc.network.type = veth
lxc.network.link = br0
lxc.network.flags = up
#lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.id_map = u 0 $subuid $subgid
lxc.id_map = g 0 $subuid $subgid
EOF
    fi
}


#
# Container creation as the newly created user
#

make_container () {
    local user=$1
    local userbox=$2
    su - $user
    $CGM movepid all $user $$
    lxc-create -n $userbox -t download -- -d debian -r jessie -a amd64
}

configure_container () {
    local user=$1
    local userbox=$2
    local ip=$3
    local gw=$4
    cat >> /home/${user}/.local/share/lxc/${userbox}/config <<EOF
lxc.network.ipv4 = $ip
lxc.network.ipv4.gateway = $gw
EOF
}

configure_inside_container () {
    # deletion of the dhclient from the container
    # lxc-usernsexec echo|cat|whatever /home/$USER...
    # if root does that lxc-userrnsexec is not necessary
    :
}

_usage () {
    :
}

_initargs () {
    :
}

_validateargs () {
    :
}

_run () {
    :
}

source ../base

initargs a b c

initcommands a b c

run $@
