#!/bin/bash

set -e

source ../utilities

# global
enable_unprivileged_containers () {
    echo 1 > /sys/fs/cgroup/cpuset/cgroup.clone_children
    echo 1 > /proc/sys/kernel/unprivileged_userns_clone
}

# per user
create_users_groups () {
    cgm create all $boxuser
    cgm chown all $boxuser $(id -u $boxuser) $(id -g $boxuser)
}

# as user
start_user_container () {
    su - $boxuser
    cgm movepid all $boxuser $$ && lxc-start -n $userbox -d
}

source ../base

initargs a b c

initcommands a b c

run $@
